[[bin]]
name = "revelcy-backend-api"
path = "src/main.rs"

[[bin]]
name = "pump-key-generator"
path = "src/bin/pump_keys_generator.rs"

[package]
name = "revelcy-backend-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7"
actix-multipart = "0.6"
actix-service = "2.0"
actix-web = { version = "4", features = ["macros"] }
anyhow = "1"
awc = { version = "3", features = ["rustls"] }
log = "0.4"
bincode = "1.3"
borsh = "0.10.4"
bs58 = "0.5"
sha2 = "0.10"
chrono = { version = "0.4", features = ["clock", "serde"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9.0"
rand = "0.8"
base64 = "0.21"
dotenvy = "0.15"
sqlx = { version = "0.6", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "migrate","uuid", "chrono"] }
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4", "serde"] }
solana-client = "2.3.1"
solana-sdk = "2.3.1"
solana-transaction-status = "2.3.5"
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
dotenv = "0.15.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
tracing = "0.1.41"
rayon = "1.10"
rand_chacha = "0.3"
regex = "1.11.2"
reqwest = "0.12.23"
